# Generated by Django 5.0.2 on 2024-03-01 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=500)),
                ('availability', models.CharField(blank=True, choices=[('in stock', 'In stock'), ('out of stock ', 'Out of stock')], default='', max_length=200, null=True)),
                ('pieces', models.IntegerField()),
                ('sku', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('image', models.FileField(upload_to='')),
                ('image1', models.FileField(upload_to='')),
                ('image2', models.FileField(upload_to='')),
                ('image3', models.FileField(upload_to='')),
                ('Tag', models.CharField(choices=[('new', 'new'), ('trendding', 'trendding'), ('sale', 'sale')], default='', max_length=250, null=True)),
                ('cid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='adminapp.category')),
                ('sid', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.subcategory')),
                ('vid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.vendor')),
            ],
        ),
    ]
