# Generated by Django 5.0.2 on 2024-04-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
